# makefile all
# auther: Hitham @ 2017
all:
	(cd makefeatures; make)
	(cd AdaBoost; make)
	(cd BAG; make)
	(cd GMM; make)
	(cd KNN; make)
	(cd MinDist; make)
	(cd RandomForests; make)
	(cd Softmax; make)
	(cd SVM; make)
clean:
	(cd makefeatures; make clean)
	(cd AdaBoost; make clean)
	(cd BAG; make clean)
	(cd GMM; make clean)
	(cd KNN; make clean)
	(cd MinDist; make clean)
	(cd RandomForests; make clean)
	(cd Softmax; make clean)
	(cd SVM; make clean)
